name: ml_sammi
channels:
  - defaults
dependencies:
  - python=3.11.4
  - ipykernel
  - pip=23.3.1
  - pip:
    - catboost==1.2.5
    - numpy==1.26.1
    - pandas==2.1.4
    - matplotlib==3.8.0
    - requests==2.31.0
    - scikit-learn==1.4.2
    - routingpy==1.3.0
    - openpyxl==3.1.3
    - ipykernel==6.29.4
    - xlrd==2.0.1
    - plotly==5.22.0
    - xgboost==2.0.3
    - lightgbm==4.3.0
    - nbformat>=4.2.0
    - seaborn==0.12.2
    - shap==0.44.1
    - lime==0.2.0.1
    - optuna==3.5.0
    - ydata-profiling==4.7.0
    - ipywidgets==8.1.3
